### ISSUE TITLE
Support for Custom Styling of Diff Highlights

### ISSUE THREAD

**Issue by zoghot** [LittleWhite-Hai/react-diff-viz#1]
I've been using react-diff-viz in my project and find it very useful. However, I've noticed that there's currently no way to customize the styling of the diff highlights (i.e., the background colors used to show changes).

Feature request:
1. Allow users to pass custom colors for additions, deletions, and modifications.
2. Optionally, support passing a custom CSS class for more advanced styling.

This would greatly enhance the component's flexibility, allowing it to better integrate with various UI designs and themes.

Possible implementation:
Add new optional props to the Diff component, such as:

```typescript
interface DiffProps {
  // ... existing props
  additionColor?: string;
  deletionColor?: string;
  modificationColor?: string;
  diffHighlightClass?: string;
}
```

These could then be used within the component to apply custom styles to the diff highlights.

Is this something you'd consider adding to the project? I'd be happy to contribute a PR if you're interested in this feature.

**Comment by LittleWhite-Hai** [comment]
Thank for your trust first!
Customize highlight style  is a good idea, I have noted done this requirement, if there is a similar demand in the future, the requirement will be added to project
