### ISSUE TITLE
FR: Support for Dynamic Customization of Array Alignment Strategy

### ISSUE THREAD

**Issue by VirgoPHP** [LittleWhite-Hai/react-diff-viz#2]
Firstly, thank you for this amazing tool! The `react-diff-viz` component is extremely useful and well-designed. I have a suggestion for an enhancement that I believe would significantly improve its utility.

##### Current Functionality:
Currently, the component supports three strategies for array alignment: 
- Longest Common Subsequence (LCS)
- Align based on `data2`
- No alignment

These strategies are defined statically within the `VizItem` configuration.

##### Proposed Enhancement:
Introduce a dynamic mechanism allowing users to switch the array alignment strategy at runtime. This could be implemented via a property on the `Diff` component or through a custom handler function.

##### Benefits:
1. **Flexibility**: Users could adapt the alignment strategy based on specific scenarios or user interactions without needing to reconfigure the entire component.
2. **User Experience**: Improved control over the visualization, allowing for better handling of diverse data sets and comparison needs.
3. **Performance**: Dynamically adjusting the alignment strategy could optimize the performance for different data structures and sizes.

##### Suggested API Changes:
1. **New Prop: `arrayAlignmentStrategy`**:
   ```typescript
   type ArrayAlignmentStrategy = "lcs" | "data2" | "none" | (path: string) => "lcs" | "data2" | "none";

   <Diff arrayAlignmentStrategy="lcs" /* or a custom function */ {...otherProps} />
   ```

2. **Custom Function for Path-Based Strategy**:
   Allow users to provide a function that determines the alignment strategy based on the path:
   ```typescript
   <Diff arrayAlignmentStrategy={(path) => {
      if (path.startsWith("complexArray")) return "data2";
      return "lcs";
   }} {...otherProps} />
   ```

##### Implementation Notes:
- Modify the `alignAndDiff` function to evaluate the `arrayAlignmentStrategy` prop and apply the selected strategy dynamically.
- Ensure backward compatibility by defaulting to the current static configuration if `arrayAlignmentStrategy` is not provided.

##### Conclusion:
This enhancement would provide developers with greater control and flexibility over the diff visualization process, making `react-diff-viz` even more powerful and adaptable to various use cases.

**Comment by LittleWhite-Hai** [comment]
solved, update to 1.2.24
